project:
  title: "future.p2p: Peer-to-Peer Compute Clusters in R"
  
format:
  revealjs:
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: images/future-logo.png
    footer: <https://future.p2p.futureverse.org>
    slide-number: true
    code-line-numbers: false
    margin: 0.05
    pointer:
      pointerSize: 32

revealjs-plugins:
  - pointer
  - bsicons
